import { TokenType } from './token-type.js';

export const KEYWORDS: ReadonlyMap<string, TokenType> = new Map<string, TokenType>([
  ['break', TokenType.Break],
  ['class', TokenType.Class],
  ['constructor', TokenType.Constructor],
  ['continue', TokenType.Continue],
  ['defer', TokenType.Defer],
  ['do', TokenType.Do],
  ['elif', TokenType.Elif],
  ['else', TokenType.Else],
  ['extends', TokenType.Extends],
  ['false', TokenType.False],
  ['fn', TokenType.Fn],
  ['for', TokenType.For],
  ['if', TokenType.If],
  ['null', TokenType.Null],
  ['override', TokenType.Override],
  ['private', TokenType.Private],
  ['public', TokenType.Public],
  ['return', TokenType.Return],
  ['static', TokenType.Static],
  ['super', TokenType.Super],
  ['this', TokenType.This],
  ['throws', TokenType.Throws],
  ['true', TokenType.True],
  ['val', TokenType.Val],
  ['var', TokenType.Var],
  ['while', TokenType.While],
]);
