export enum TokenType {
  Colon = 'Colon',
  Comma = 'Comma',
  DoubleLiteral = 'DoubleLiteral',
  EOF = 'EOF',
  Equal = 'Equal',
  False = 'False',
  Identifier = 'Identifier',
  IntegerLiteral = 'IntegerLiteral',
  LeftBrace = 'LeftBrace',
  LeftParen = 'LeftParen',
  Null = 'Null',
  QuestionMark = 'QuestionMark',
  RightBrace = 'RightBrace',
  RightParen = 'RightParen',
  Semicolon = 'Semicolon',
  StringLiteral = 'StringLiteral',
  True = 'True',
  Val = 'Val',
  Var = 'Var',
}
